
// UI ACTIONS

export const SIDEBAR_SHOW = 'SIDEBAR_SHOW';
export const SIDEBAR_HIDE = 'SIDEBAR_HIDE';
export const SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE';

export const ALERT = 'ALERT';
export const ALERT_ADD = 'ALERT_ADD';
export const ALERT_REMOVE = 'ALERT_REMOVE';

// AUTH ACTIONS

export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_START = 'AUTH_USER_START';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAILED = 'AUTH_USER_FAILED';

export const AUTH_CHECK_TOKEN_EXPIRATION = 'AUTH_CHECK_TOKEN_EXPIRATION';
export const LOGOUT = 'LOGOUT';

// user actions

export const USER_GET_PROFILE = 'USER_GET_PROFILE';
export const USER_GET_PROFILE_START = 'USER_GET_PROFILE_START';
export const USER_GET_PROFILE_SUCCESS = 'USER_GET_PROFILE_SUCCESS';
export const USER_GET_PROFILE_FAILED = 'USER_GET_PROFILE_FAILED';

// student actions

// teacher actions

// admin actions

export const ADMIN_GET_QUESTIONS = 'ADMIN_GET_QUESTIONS';
export const ADMIN_GET_QUESTIONS_START = 'ADMIN_GET_QUESTIONS_START';
export const ADMIN_GET_QUESTIONS_SUCCESS = 'ADMIN_GET_QUESTIONS_SUCCESS';
export const ADMIN_GET_QUESTIONS_FAILED = 'ADMIN_GET_QUESTIONS_FAILED';

export const ADMIN_GET_SUBJECTS = 'ADMIN_GET_SUBJECTS';
export const ADMIN_GET_SUBJECTS_START = 'ADMIN_GET_SUBJECTS_START';
export const ADMIN_GET_SUBJECTS_SUCCESS = 'ADMIN_GET_SUBJECTS_SUCCESS';
export const ADMIN_GET_SUBJECTS_FAILED = 'ADMIN_GET_SUBJECTS_FAILED';

export const ADMIN_GET_LESSONS = 'ADMIN_GET_LESSONS';
export const ADMIN_GET_LESSONS_START = 'ADMIN_GET_LESSONS_START';
export const ADMIN_GET_LESSONS_SUCCESS = 'ADMIN_GET_LESSONS_SUCCESS';
export const ADMIN_GET_LESSONS_FAILED = 'ADMIN_GET_LESSONS_FAILED';

export const ADMIN_CREATE_QUESTION = 'ADMIN_CREATE_QUESTION';
export const ADMIN_CREATE_QUESTION_START = 'ADMIN_CREATE_QUESTION_START';
export const ADMIN_CREATE_QUESTION_SUCCESS = 'ADMIN_CREATE_QUESTION_SUCCESS';
export const ADMIN_CREATE_QUESTION_FAILED = 'ADMIN_CREATE_QUESTION_FAILED';

export const ADMIN_DELETE_QUESTION = 'ADMIN_DELETE_QUESTION';
export const ADMIN_DELETE_QUESTION_START = 'ADMIN_DELETE_QUESTION_START';
export const ADMIN_DELETE_QUESTION_SUCCESS = 'ADMIN_DELETE_QUESTION_SUCCESS';
export const ADMIN_DELETE_QUESTION_FAILED = 'ADMIN_DELETE_QUESTION_FAILED';